apiVersion: v2
name: porkbun-dns-updater-helm
description: A Kubernetes CronJob that updates porkbun DNS with the current machine's public IP
type: application

# These versions will be automatically updated by GitHub Action on release.
version: 0.0.1
appVersion: 0.0.1
