name: Release

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write   # required to create a GitHub Release
  packages: write   # required to push to GHCR

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      CHART_PATH: ./helm
      DOCKER_CONTEXT: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Docker Build & Push
      - name: Set up Docker Buildx for Multiarch Image
        uses: docker/setup-buildx-action@v3
      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{ github.ref_name }}
      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.DOCKER_CONTEXT }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Helm Build & Push
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Update and Package Helm chart
        env:
          CHART_VERSION: ${{ github.ref_name }}
        run: |
          echo "Updating $CHART_PATH/Chart.yaml to version $CHART_VERSION"
          
          sed -i "s/^version: .*/version: $CHART_VERSION/" $CHART_PATH/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: $CHART_VERSION/" $CHART_PATH/Chart.yaml
          
          echo "--- Updated Chart.yaml ---"
          cat $CHART_PATH/Chart.yaml
          helm package $CHART_PATH
      - name: Create GitHub Release and Upload Helm Chart
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ./*.tgz
